version: 2
jobs:
  build:
    working_directory: ~/naive-ui-change-theme
    docker:
      - image: node:18.16.0

    # 步骤定义
    steps:
      # 拉取代码
      - checkout

      # 安装pnpm
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate

      # 恢复缓存
      - restore_cache:
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      # 安装依赖
      - run:
          name: Install Dependencies
          command: pnpm install

      # 保存缓存
      - save_cache:
          paths:
            - node_modules
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      # Build打包
      - run:
          name: Build project
          command: pnpm run build

      # 推送dist至GitHub
      - run:
          name: Deploy to GitHub
          command: |
            cd dist
            git config --global init.defaultBranch main
            git init
            git config user.name "liub1934"
            git config user.email "liub1934@gmail.com"
            git add .
            git commit -m "Push Dist"
            git push -f https://$GITHUB_TOKEN@github.com/liub1934/naive-ui-change-theme.git main:gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
